name: Space CI/CD Pipeline

# This workflow uses the shared infrastructure pipeline
# Copy this file to .github/workflows/ci-cd.yml in each space

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly health checks
    - cron: '0 2 * * 0'

jobs:
  # Use the shared infrastructure pipeline
  shared-pipeline:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      space_name: ${{ github.repository_name }}  # Will be overridden per space
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      skip_framework_tasks: true  # Override to false for HUMAN-AI-FRAMEWORK space
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

  # Space-specific jobs (if needed)
  space-specific-setup:
    runs-on: ubuntu-latest
    needs: shared-pipeline
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Space-specific configuration
        run: |
          # Add any space-specific setup here
          echo "🔧 Running space-specific configuration..."
          
          # Example: Set space-specific environment variables
          echo "SPACE_NAME=${{ github.repository_name }}" >> $GITHUB_ENV
          
          # Example: Configure space-specific integrations
          if [[ -f "space-config.json" ]]; then
            echo "📋 Loading space-specific configuration..."
            cat space-config.json
          fi
          
          echo "✅ Space-specific setup completed"