name: Automation Workflow

on:
  workflow_dispatch:

jobs:
  repair-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: actions/setup-node@v3
        with:
          node-version: 16
