kname: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          # workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          # service_account: my-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & Deploy
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/miller-maps
          gcloud run deploy miller-maps \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/miller-maps \
            --region us-central1 \
            --platform managed

