name: Publish Dashboard to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  REPO: ${{ github.repository }}
  TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install & Build (if applicable)
        if: file-exists('package.json') && file-exists('npm run build')
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: .
          deploy_branch: gh-pages

      - name: Configure GitHub Pages
        run: |
          curl -X POST \
            -H "Authorization: token ${GH_PAGES_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}'